# Dependabot configuration for automated dependency updates
# This configuration helps keep dependencies up-to-date and secure
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Enable updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"  # Look for pip dependencies in the root directory
    schedule:
      interval: "daily"  # Check for updates daily
      time: "06:00"     # At 6 AM UTC
      timezone: "UTC"
    open-pull-requests-limit: 10  # Maximum number of open PRs
    reviewers:
      - "suqianye2000"  # Request review from maintainer
    assignees:
      - "suqianye2000"  # Assign PRs to maintainer
    commit-message:
      prefix: "deps"    # Prefix commit messages with 'deps'
      include: "scope"  # Include dependency scope in commit message
    # Group updates by dependency type
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "coverage*"
          - "black*"
          - "flake8*"
          - "mypy*"
          - "sphinx*"
          - "pre-commit*"
      development-dependencies:
        patterns:
          - "pytest*"
          - "coverage*"
          - "black*"
          - "flake8*"
          - "mypy*"
          - "sphinx*"
          - "pre-commit*"
    # Ignore specific dependencies that require manual updates
    ignore:
      - dependency-name: "python"  # Don't auto-update Python version requirements
        update-types: ["version-update:semver-major"]
    # Enable security-only updates for major versions
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Auto-merge patch and minor updates for production dependencies
    rebase-strategy: "auto"

  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  # Check for GitHub Actions updates weekly
      day: "monday"       # On Mondays
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "suqianye2000"
    assignees:
      - "suqianye2000"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"
