# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Set the default stage to commit, only checking during submission
default_stages:
  - pre-commit

# Set the default language version
default_language_version:
  python: python3.10  # Use current environment Python version

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        types: [python]
        exclude: ^docs/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        types: [python]
        exclude: ^docs/
