# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Use conda/mamba for package management
conda:
  environment: docs/environment.yml

# Use standard Python build instead of custom commands
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Use standard Sphinx build process for better cross-reference support
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Standard build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      # Set environment variables to skip Fortran compilation
      - export SKYBORN_DOCS_BUILD=1
      - export SKIP_FORTRAN=1
      - export SPHINX_WARN_AS_ERROR=0
      # Add source to Python path for imports
      - export PYTHONPATH="${PYTHONPATH}:${PWD}/src"
    post_build:
      # Validate that key pages and cross-references exist
      - test -f $READTHEDOCS_OUTPUT/html/functions_classes.html && echo "✅ Functions page generated" || echo "⚠️ Functions page missing"
      - test -f $READTHEDOCS_OUTPUT/html/api/conversion.html && echo "✅ API pages generated" || echo "⚠️ API pages missing"
      # Test a specific cross-reference link
      - grep -q 'href="api/conversion.html#skyborn.conversion.grib_to_netcdf"' $READTHEDOCS_OUTPUT/html/functions_classes.html && echo "✅ Cross-references working" || echo "⚠️ Cross-references broken"
