# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Use conda/mamba for package management
conda:
  environment: docs/environment.yml

# Install only documentation dependencies (package compiled in build stage)
python:
  install:
    - requirements: requirements-docs.txt

# Use standard Sphinx build process for better cross-reference support
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Minimal build configuration for documentation
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
