# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - python -m pip install --upgrade pip setuptools wheel
    post_install:
      - python -m pip install -e .
      - cd docs && python build_docs.py --clean
      - cp -r docs/build/html/* $READTHEDOCS_OUTPUT/html/

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .

# Skip default sphinx build since we use custom build_docs.py
# The script will generate all necessary files including the particle effect homepage
