# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  commands:
    # Setup compiler environment variables and create symlinks
    - export FC=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gfortran
    - export F77=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gfortran
    - export F90=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gfortran
    - export CC=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc
    - export CXX=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-g++
    - export PATH=$CONDA_PREFIX/bin:$PATH
    # Create symlinks for meson to find compilers
    - mkdir -p $HOME/bin
    - ln -sf $CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gfortran $HOME/bin/gfortran
    - ln -sf $CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc $HOME/bin/gcc
    - ln -sf $CONDA_PREFIX/bin/x86_64-conda-linux-gnu-g++ $HOME/bin/g++
    - export PATH=$HOME/bin:$PATH
    # Verify compiler availability
    - which gfortran && gfortran --version
    - which gcc && gcc --version
    # Install Python dependencies
    - python -m pip install --upgrade pip setuptools wheel
    - python -m pip install -r requirements-docs.txt
    - python -m pip install -e .
    # Build documentation with custom script
    - export LC_ALL=C.UTF-8 && export LANG=C.UTF-8 && cd docs && python build_docs.py --clean
    # Copy to output directory
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r docs/build/html/* $READTHEDOCS_OUTPUT/html/
    - echo "✅ Custom build completed with particle effect homepage"
    # Debug: Check what files were copied
    # - echo "📁 Files in output directory:"
    # - ls -la $READTHEDOCS_OUTPUT/html/
    # - echo "🔍 Content of index.html (first 5 lines):"
    # - head -5 $READTHEDOCS_OUTPUT/html/index.html
    # - echo "🔍 Checking if particles-canvas exists in index.html:"
    # - grep -c "particles-canvas" $READTHEDOCS_OUTPUT/html/index.html || echo "❌ particles-canvas not found"
