# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  commands:
    # Set environment variables to skip Fortran compilation
    - export SKYBORN_DOCS_BUILD=1
    - export SKIP_FORTRAN=1
    # Install documentation requirements
    - python -m pip install --upgrade pip setuptools wheel
    - python -m pip install -r requirements-docs.txt
    # Try to install package in docs mode, continue if fails
    - python -m pip install -e . || echo "⚠️  Package install failed, continuing with docs-only build"
    # Test if we can import basic modules
    - python -c "import sys; sys.path.insert(0, '.');
      try:from skyborn import calculations;
          from skyborn import mann_kendall;
          from skyborn import interpolation;
          print('✅ Successfully imported Python-only modules');
      except ImportError as e:print(f'ℹ️  Some modules not available:{e}');
          print('ℹ️  Continuing with documentation build...');"
    # Build documentation
    - export LC_ALL=C.UTF-8 && export LANG=C.UTF-8 && cd docs && python build_docs.py --clean
    # Copy to output directory
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r docs/build/html/* $READTHEDOCS_OUTPUT/html/
    - echo "✅ Documentation build completed"
    # Debug: Check what files were copied
    # - echo "📁 Files in output directory:"
    # - ls -la $READTHEDOCS_OUTPUT/html/
    # - echo "🔍 Content of index.html (first 5 lines):"
    # - head -5 $READTHEDOCS_OUTPUT/html/index.html
    # - echo "🔍 Checking if particles-canvas exists in index.html:"
    # - grep -c "particles-canvas" $READTHEDOCS_OUTPUT/html/index.html || echo "❌ particles-canvas not found"
