# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Install system dependencies including gfortran
      - apt-get update
      - apt-get install -y gfortran gcc g++ build-essential
  commands:
    # Install dependencies
    - python -m pip install --upgrade pip setuptools wheel
    - python -m pip install -r requirements-docs.txt
    - python -m pip install -e .
    # Build documentation with custom script
    - export LC_ALL=C.UTF-8 && export LANG=C.UTF-8 && cd docs && python build_docs.py --clean
    # Copy to output directory
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r docs/build/html/* $READTHEDOCS_OUTPUT/html/
    - echo "✅ Custom build completed with particle effect homepage"
    # Debug: Check what files were copied
    # - echo "📁 Files in output directory:"
    # - ls -la $READTHEDOCS_OUTPUT/html/
    # - echo "🔍 Content of index.html (first 5 lines):"
    # - head -5 $READTHEDOCS_OUTPUT/html/index.html
    # - echo "🔍 Checking if particles-canvas exists in index.html:"
    # - grep -c "particles-canvas" $READTHEDOCS_OUTPUT/html/index.html || echo "❌ particles-canvas not found"
