# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Use conda/mamba for package management
conda:
  environment: docs/environment.yml

# Only install documentation dependencies, NOT the package itself
python:
  install:
    - requirements: requirements-docs.txt

# Use standard Sphinx build process for better cross-reference support
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Standard build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      # Critical: Set environment variables to prevent ANY compilation attempts
      - export SKYBORN_DOCS_BUILD=1
      - export SKIP_FORTRAN=1
      - export SKIP_COMPILATION=1
      - export SPHINX_WARN_AS_ERROR=0
      # Disable setuptools from trying to build extensions
      - export SETUPTOOLS_USE_DISTUTILS=stdlib
      # Add source to Python path so Sphinx can import modules directly
      - export PYTHONPATH="${PWD}/src:${PYTHONPATH}"
      # Verify the path setup
      - echo "Python path: $PYTHONPATH"
      - ls -la src/skyborn/ || echo "Source directory check"
    post_build:
      # Validate that key pages and cross-references exist
      - test -f $READTHEDOCS_OUTPUT/html/functions_classes.html && echo "✅ Functions page generated" || echo "⚠️ Functions page missing"
      - test -f $READTHEDOCS_OUTPUT/html/api/conversion.html && echo "✅ API pages generated" || echo "⚠️ API pages missing"
      # Test a specific cross-reference link
      - grep -q 'href="api/conversion.html#skyborn.conversion.grib_to_netcdf"' $READTHEDOCS_OUTPUT/html/functions_classes.html && echo "✅ Cross-references working" || echo "⚠️ Cross-references broken"
