# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Use conda/mamba for package management
conda:
  environment: docs/environment.yml

# Install documentation dependencies AND the package with compilation
python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Use standard Sphinx build process for better cross-reference support
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Standard build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      # Set environment variables to help compilation succeed
      - export SKYBORN_DOCS_BUILD=1
      - export SPHINX_WARN_AS_ERROR=0
      # Set up compilation environment
      - export CC=gcc
      - export FC=gfortran
      - export PKG_CONFIG_PATH="${CONDA_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
      # Ensure meson can find tools
      - which meson || echo "Meson not found"
      - which ninja || echo "Ninja not found"
      - which gcc || echo "GCC not found"
      - which gfortran || echo "Gfortran not found"
      # Check source structure
      - ls -la src/skyborn/ || echo "Source directory check"
    post_build:
      # Validate that key pages and cross-references exist
      - test -f $READTHEDOCS_OUTPUT/html/functions_classes.html && echo "Functions page generated" || echo "Functions page missing"
      - test -f $READTHEDOCS_OUTPUT/html/api/conversion.html && echo "API pages generated" || echo "API pages missing"
      # Test a specific cross-reference link
      - grep -q 'href="api/conversion.html#skyborn.conversion.grib_to_netcdf"' $READTHEDOCS_OUTPUT/html/functions_classes.html && echo "Cross-references working" || echo "Cross-references broken"
