# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    # Install dependencies
    - python -m pip install --upgrade pip setuptools wheel
    - python -m pip install -r requirements-docs.txt
    - python -m pip install -e .
    # Build documentation with custom script
    - export LC_ALL=C.UTF-8 && export LANG=C.UTF-8 && cd docs && python build_docs.py --clean
    # Copy to output directory
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r docs/build/html/* $READTHEDOCS_OUTPUT/html/
    # Since Read the Docs might override index.html, let's ensure our particle effect page is accessible
    # Copy particle effect page to entrance.html as backup
    - cp $READTHEDOCS_OUTPUT/html/index.html $READTHEDOCS_OUTPUT/html/entrance.html
    - echo "✅ Custom build completed with particle effect homepage"
    - echo "🎯 Particle effect page: index.html"
    - echo "🎯 Backup particle page: entrance.html"
    - echo "📖 Documentation: documentation.html"
