name: skyborn
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - xarray
  - matplotlib
  - seaborn
  - pytest
  - pytest-cov
  - eccodes # For GRIB processing
  - pip
  - pip:
      - -e .
