C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.26.4)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapdzeps (dzepsf2pywrap, x)
      external dzeps
      double precision x
      real dzepsf2pywrap
      real  dzeps
      dzepsf2pywrap = dzeps(x)
      end


      subroutine f2pywrappimach (pimachf2pywrap)
      external pimach
      real pimachf2pywrap
      real  pimach
      pimachf2pywrap = pimach()
      end


      subroutine f2pywrapindx (indxf2pywrap, m, n, nlat)
      external indx
      integer m
      integer n
      integer nlat
      integer indxf2pywrap
      integer  indx
      indxf2pywrap = indx(m, n, nlat)
      end


      subroutine f2pyinithrf(setupfunc)
      external setupfunc
      real tfft
      common /hrf/ tfft
      call setupfunc(tfft)
      end
