"""Compatibility shims for regridding helpers during plot migration."""

from __future__ import annotations

from ._adapters import cartopy_vector as _cartopy_vector
from ._adapters import grid_prepare as _grid_prepare

_default_cartopy_target_extent = _cartopy_vector._default_cartopy_target_extent
_build_projection_target_grid = _cartopy_vector._build_projection_target_grid
_extract_regular_grid_from_regridded_vectors = (
    _cartopy_vector._extract_regular_grid_from_regridded_vectors
)
_regrid_cartopy_vectors = _cartopy_vector._regrid_cartopy_vectors

_normalize_regrid_shape = _grid_prepare._normalize_regrid_shape
_normalize_density_pair = _grid_prepare._normalize_density_pair
_is_curvilinear_grid = _grid_prepare._is_curvilinear_grid
_default_curvilinear_regrid_shape = _grid_prepare._default_curvilinear_regrid_shape
_build_curvilinear_target_grid = _grid_prepare._build_curvilinear_target_grid
_rcm2rgrid_2d = _grid_prepare._rcm2rgrid_2d
_rcm2rgrid_fields = _grid_prepare._rcm2rgrid_fields
_maybe_as_scalar_field = _grid_prepare._maybe_as_scalar_field
_regrid_curvilinear_vectors = _grid_prepare._regrid_curvilinear_vectors
_prepare_source_vector_grid = _grid_prepare._prepare_source_vector_grid
_grid_spans_full_longitude = _grid_prepare._grid_spans_full_longitude
_has_cyclic_longitude_endpoint = _grid_prepare._has_cyclic_longitude_endpoint
_append_cyclic_column = _grid_prepare._append_cyclic_column
_wrap_periodic_grid_queries = _grid_prepare._wrap_periodic_grid_queries
