# Environment file for Read the Docs documentation build
name: skyborn-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - setuptools
  - wheel
  # Documentation dependencies
  - sphinx>=4.0
  - sphinx-book-theme
  - myst-nb
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - toml
  # Minimal scientific packages needed for docs (no compilation required)
  - numpy
  - pandas
  - meson
  - ninja
  - gcc
  - gfortran
  # NOTE: We intentionally DON'T install the actual skyborn package
  # to avoid compilation issues. Sphinx will use PYTHONPATH + mocking.
