name: skyborn-docs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gcc_linux-64  # GCC compiler for Linux
  - gfortran_linux-64  # GFortran compiler for Linux
  - binutils_linux-64  # Binutils for linking
  - cmake
  - ninja
  - meson
  - pkg-config
  - numpy
  - scipy
  - pip
  - pip:
    - sphinx
    - sphinx-book-theme
    - myst-parser
    - nbsphinx
    - jupyter
