# Environment file for Read the Docs documentation build
name: skyborn-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - setuptools
  - wheel
  # Documentation dependencies
  - sphinx>=4.0
  - sphinx-book-theme
  - myst-nb
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - toml
  # Scientific packages and compilation tools needed for skyborn
  - numpy
  - pandas
  # Compilation tools for Fortran and Cython modules
  - meson
  - ninja
  - c-compiler      # Modern conda-forge C compiler
  - fortran-compiler # Modern conda-forge Fortran compiler
  - pkg-config
  # Build tools
  - make
  - cmake
  # Additional scientific dependencies that might be needed
  - scipy
  - matplotlib-base
  - cython
  # NOTE: We need compilation tools to build skyborn's Fortran/Cython extensions
  # so that Sphinx can generate proper cross-references
