# Environment file for Read the Docs documentation build
name: skyborn-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - setuptools
  - wheel
  # Documentation dependencies
  - sphinx>=4.0
  - sphinx-book-theme
  - myst-nb
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - toml
  # Scientific packages for documentation and compilation
  - numpy
  - pandas
  - scipy
  - matplotlib-base
  - xarray  # Required by skyborn.calc.calculations
  # Build tools (following build-wheels.yml configuration)
  - meson>=1.0
  - ninja
  - gcc  # C compiler
  - gfortran  # Fortran compiler (like your wheel builds)
  - cython>=3.0.0
  # NOTE: Now enabling compilation to match your setup.py design
