# Environment file for Read the Docs documentation build
name: skyborn-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - setuptools
  - wheel
  # Documentation dependencies
  - sphinx>=4.0
  - sphinx-book-theme
  - myst-nb
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - toml
  # Scientific packages for documentation (needed for imports)
  - numpy
  - pandas
  - scipy
  - matplotlib-base
  - xarray  # Required by skyborn.calc.calculations
  # NOTE: Using documentation-only approach with mocked imports
  # No compilation tools needed since we mock all compiled modules
