name: skyborn-docs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gfortran
  - gcc
  - cxx-compiler
  - cmake
  - ninja
  - meson
  - pkg-config
  - numpy
  - scipy
  - pip
  - pip:
    - sphinx
    - sphinx-book-theme
    - myst-parser
    - nbsphinx
    - jupyter
