# GitHub Actions workflow for building and deploying Sphinx documentation to GitHub Pages
name: "Deploy Documentation"

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/docs-deploy.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-docs.txt
          pip install -e .

      - name: Build English documentation
        run: |
          cd docs
          python build_docs.py --lang en --clean

      - name: Build Chinese documentation
        run: |
          cd docs
          python build_docs.py --lang zh_CN --clean

      - name: Prepare GitHub Pages structure
        run: |
          mkdir -p _site

          # Check if documentation was built successfully
          if [ ! -d "docs/build/en/html" ]; then
            echo "Error: English documentation not found at docs/build/en/html"
            find docs/build -type d -name "html" || echo "No html directories found"
            exit 1
          fi

          if [ ! -d "docs/build/zh_CN/html" ]; then
            echo "Error: Chinese documentation not found at docs/build/zh_CN/html"
            find docs/build -type d -name "html" || echo "No html directories found"
            exit 1
          fi

          # Copy documentation
          cp -r docs/build/en/html/* _site/
          mkdir -p _site/zh_CN
          cp -r docs/build/zh_CN/html/* _site/zh_CN/
          mkdir -p _site/en
          cp -r docs/build/en/html/* _site/en/

          # Create language selector
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <title>Skyborn Documentation</title>
              <meta http-equiv="refresh" content="0; url=./en/">
              <style>
                  body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
                  .language-selector { margin: 20px; }
                  .language-selector a {
                      display: inline-block; margin: 10px; padding: 15px 30px;
                      background-color: #007acc; color: white; text-decoration: none;
                      border-radius: 5px;
                  }
                  .language-selector a:hover { background-color: #005999; }
              </style>
          </head>
          <body>
              <h1>Skyborn Documentation</h1>
              <div class="language-selector">
                  <a href="./en/">English Documentation</a>
                  <a href="./zh_CN/">中文文档</a>
              </div>
              <p>Redirecting to English documentation...</p>
          </body>
          </html>
          EOF

          # Debug: Show what was created
          echo "Site structure:"
          find _site -type f -name "*.html" | head -5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
