name: Publish Python Package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (build only, do not publish)"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build package
        run: python -m build

      - name: Show build info
        run: |
          echo "Built packages:"
          ls -la dist/
          echo "Package contents:"
          if [ -f dist/*.whl ]; then
            python -m zipfile -l dist/*.whl | head -20
          fi

      - name: Publish to PyPI
        if: ${{ !inputs.dry_run }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Dry run completed
        if: ${{ inputs.dry_run }}
        run: |
          echo "🎯 Dry run completed successfully!"
          echo "Package built but not published."
          echo "Remove 'dry_run' option to publish for real."
