# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish Python Package

on:
  release:
    types: [published]
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (optional, will use current version if empty)"
        required: false
        type: string
      dry_run:
        description: "Dry run (build only, do not publish)"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build

      - name: Show build info
        run: |
          echo "Built packages:"
          ls -la dist/
          echo "Package contents:"
          if [ -f dist/*.whl ]; then
            python -m zipfile -l dist/*.whl | head -20
          fi

      - name: Publish package
        if: ${{ !inputs.dry_run }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Dry run completed
        if: ${{ inputs.dry_run }}
        run: |
          echo "🎯 Dry run completed successfully!"
          echo "Package built but not published."
          echo "Remove 'dry_run' option to publish for real."
