name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: skyborn
          auto-activate-base: false

      - name: Check workspace
        run: echo ${{ github.workspace }}

      - name: Install package in development mode
        shell: bash -l {0}
        run: pip install -e .

      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      # - name: Test with pytest
      #   shell: bash -l {0}
      #   run: python -m pytest
